name: integration-test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.6.3', '3.9.2' ]

    name: maven ${{ matrix.maven }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up JDK 11 and maven for running tests
        uses: s4u/setup-maven-action@v1.9.0
        with:
          java-version: 11
          distribution: 'temurin'
          maven-version: ${{ matrix.maven }}
      - name: Install chromium
        run: 'sudo apt-get install chromium-chromedriver -y'
      - name: Prepare all poms
        # Integration tests need the agent jar and all classes to be compiled
        # and installed locally.
        run: 'mvn install -DskipTests'
      - name: Run the integration tests
        run: 'mvn failsafe:integration-test failsafe:verify -pl main'
