name: tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 for running tests
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Style check using spotless
        run: 'mvn spotless:check'
      - name: Create agent jar # We need the agent before we run tests
        run: 'mvn package -DskipTests'
      - name: Run test phase
        run: 'mvn test'
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
