name: tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.6.3', '3.9.2' ]

    name: maven ${{ matrix.maven }}

    steps:
      - name: Set up JDK 11 and maven for running tests
        uses: s4u/setup-maven-action@v1.9.0
        with:
          java-version: 11
          distribution: 'temurin'
          maven-version: ${{ matrix.maven }}
      - name: Style check using spotless
        run: 'mvn spotless:check'
      - name: Prepare all poms
        # We need the poms to be ready before we run tests
        # And we cannot run tests in the same step as we need the agent jar
        run: 'mvn install -DskipTests'
      - name: Run test phase
        run: 'mvn test'
