name: tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 for running tests
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Style check using spotless
        run: 'mvn spotless:check'
      - name: Prepare all poms
        # We need the poms to be ready before we run tests
        # And we cannot run tests in the same step as we need the agent jar
        # Includes test of matched-line-finder
        run: 'mvn install -pl se.assertkth:collector-sahab-parent-pom,commons,matched-line-finder'
      - name: Create agent jar # We need the agent before we run tests
        run: 'mvn package -DskipTests -pl trace-collector'
      - name: Run test phase
        run: 'mvn test -pl trace-collector'
